import type { User } from "../types";

const URL_API = "http://localhost:5070";
const myHeaders = new Headers({
    "Content-Type": "application/json"
});

export const getUser = async (): Promise<User[] | null> => {
    try {
        const response = await fetch(`${URL_API}/api/User`, {
            method: 'GET',
            headers: myHeaders
        });

        switch (response.status) {
            case 200:
                const data: User[] = await response.json();
                return data;
            case 401:
                console.error("No autorizado o token inv√°lido");
                break;
            case 404:
                console.error("El User no existe");
                break;
            default:
                console.error("Error inesperado. Contacte al administrador.");
        }
    } catch (error) {
        console.error("Error de red o servidor:", error);
    }

    return null; // en caso de error
};

export const postUser = async (datos: User): Promise<any | undefined> => {
    try {
        // Remove id if present
        const { id, ...userData } = datos;
        console.log("Datos enviados a postUser:", userData);

        const response = await fetch(`${URL_API}/api/User`, {
            method: "POST",
            headers: myHeaders,
            body: JSON.stringify(userData)
        });
        if (!response.ok) {
            const errorText = await response.text();
            console.error(`Error en la solicitud POST: ${response.status} - ${errorText}`);
            return undefined;
        }
        return await response.json();
    } catch (error) {
        console.error('Error en la solicitud POST:', error);
    }
}

export const putUser = async (datos: User, id: number | string): Promise<Response | undefined> => {
    try {
        return await fetch(`${URL_API}/api/User/${id}`, {
            method: "PUT",
            headers: myHeaders,
            body: JSON.stringify(datos)
        });
    } catch (error) {
        console.error('Error en la solicitud PUT:', error);
    }
}

export const deleteUser = async (id: number | string): Promise<Response | undefined> => {
    try {
        const response = await fetch(`${URL_API}/api/User/${id}`, {
            method: "DELETE",
            headers: myHeaders,
        });
        if (!response.ok) {
            const errorText = await response.text();
            console.error(`Error en la solicitud DELETE: ${response.status} - ${errorText}`);
        }
        return response;
    } catch (error) {
        console.error('Error en la solicitud DELETE:', error);
    }
}